import 'dotenv/config';
import { appendFile } from 'node:fs/promises';
import type { Pool as PgPool } from 'pg';
import WebSocket from 'ws';
import { getReferencePrice } from './reference_prices.js';
import { nextWebsocketEndpoint, normalizeWebsocketEndpoints, type WebsocketEndpointInput } from './evm_ws_rotation.js';

export const UNISWAP_V3_BASE_FACTORY = (process.env.UNISWAP_V3_BASE_FACTORY ?? '0x33128a8fC17869897dcE68Ed026d694621f6FDfD').toLowerCase();
const SWAP_TOPIC = '0xc42079f94a6350d7e6235f29174924f928cc2ac818eb64fed8004e115fbcca67';
const WETH = (process.env.UNISWAP_V3_BASE_WETH ?? '0x4200000000000000000000000000000000000006').toLowerCase();
const USDC = (process.env.UNISWAP_V3_BASE_USDC ?? '0x833589fcd6edb6e08f4c7c32d4f71b54bda02913').toLowerCase();
const ZERO = '0x0000000000000000000000000000000000000000';
const SWAP_THRESHOLD = Number(process.env.UNISWAP_V3_BASE_SWAP_THRESHOLD ?? process.env.EVM_PROMOTION_SWAP_THRESHOLD ?? process.env.PROMOTION_SWAP_THRESHOLD ?? 100);
const WALLET_THRESHOLD = Number(process.env.UNISWAP_V3_BASE_MIN_UNIQUE_WALLETS ?? process.env.EVM_PROMOTION_MIN_UNIQUE_WALLETS ?? process.env.PROMOTION_MIN_UNIQUE_WALLETS ?? 20);
const WINDOW_MS = Number(process.env.PROMOTION_WINDOW_MS ?? 15 * 60 * 1000);
const FAILURE_FILE = process.env.UNISWAP_V3_BASE_FAILURE_FILE ?? 'uniswap-v3-base-failures.jsonl';
const PRICE_FILE = process.env.UNISWAP_V3_BASE_PRICE_EVENT_FILE ?? 'uniswap-v3-base-price-events.jsonl';
const TIMEFRAMES = [{ name: '1m', milliseconds: 60_000 }, { name: '5m', milliseconds: 300_000 }, { name: '15m', milliseconds: 900_000 }, { name: '1h', milliseconds: 3_600_000 }, { name: '4h', milliseconds: 14_400_000 }, { name: '1d', milliseconds: 86_400_000 }] as const;
type Pair = { address: string; token0: string; token1: string; symbol0: string; symbol1: string; decimals0: number; decimals1: number; fee: number; spacing: number; block: number };
type Activity = { pair: Pair; events: Array<{ wallet: string; timestamp: number }> };
const word = (data: string, index: number) => { const hex = data.startsWith('0x') ? data.slice(2) : data; if (hex.length < (index + 1) * 64) throw new Error('ABI word out of range'); return BigInt(`0x${hex.slice(index * 64, (index + 1) * 64)}`); };
const addr = (value: unknown) => { const raw = String(value ?? ''); return /^0x[0-9a-f]{64}$/i.test(raw) ? `0x${raw.slice(-40)}`.toLowerCase() : ZERO; };
const uint = (value: unknown) => { try { return Number(BigInt(String(value))); } catch { return 0; } };
const text = (value: unknown) => { try { const data = String(value); const offset = Number(word(data, 0)); const length = Number(word(data, offset / 32)); return Buffer.from(data.slice(2 + (offset + 32) * 2, 2 + (offset + 32 + length) * 2), 'hex').toString('utf8').replace(/\0/g, ''); } catch { return ''; } };
const signed = (data: string, index: number) => { const raw = word(data, index); return Number(raw >= (1n << 255n) ? raw - (1n << 256n) : raw); };
const supported = (pair: Pair) => pair.token0 === WETH || pair.token1 === WETH || pair.token0 === USDC || pair.token1 === USDC;
const usd = (pair: Pair, price: number, wethUsd: number | null) => pair.token1 === USDC ? price : pair.token0 === USDC ? 1 / price : pair.token1 === WETH && wethUsd ? price * wethUsd : pair.token0 === WETH && wethUsd ? wethUsd / price : null;
async function failure(address: string, error: unknown) { try { await appendFile(FAILURE_FILE, `${JSON.stringify({ timestamp: new Date().toISOString(), poolAddress: address, error: String(error) })}\n`); } catch { /* best effort */ } }

async function resolve(call: (method: string, params: unknown[]) => Promise<any>, address: string, block: number): Promise<Pair | null> {
  const [a, b, fee, spacing] = await Promise.all(['0x0dfe1681', '0xd21220a7', '0xddca3f43', '0xd0c93a7c'].map((data) => call('eth_call', [{ to: address, data }, 'latest'])));
  const token0 = addr(a); const token1 = addr(b); if (token0 === ZERO || token1 === ZERO) return null;
  const meta = await Promise.all([token0, token1].flatMap((token) => ['0x95d89b41', '0x313ce567'].map((data) => call('eth_call', [{ to: token, data }, 'latest']))));
  return { address, token0, token1, symbol0: text(meta[0]) || 'TOKEN0', decimals0: uint(meta[1]), symbol1: text(meta[2]) || 'TOKEN1', decimals1: uint(meta[3]), fee: uint(fee), spacing: signed(String(spacing), 0), block };
}

export async function startUniswapV3BaseIndexer(pgPool: PgPool, websocketUrl: WebsocketEndpointInput, priceFile = PRICE_FILE): Promise<void> {
  const endpoints = normalizeWebsocketEndpoints(websocketUrl);
  if (endpoints.length === 0) { console.warn('[uniswap-v3-base] no websocket endpoints configured; indexing is disabled.'); return; }
  const activities = new Map<string, Activity>(); const promoted = new Set<string>(); let socket: WebSocket | undefined; let endpointIndex = 0; let id = 1; let delay = 1000; let reconnect: NodeJS.Timeout | undefined; let wethUsd: number | null = null; const pending = new Map<number, { resolve: (value: any) => void; reject: (error: Error) => void }>();
  const rpc = (method: string, params: unknown[]) => new Promise<any>((resolvePromise, reject) => { if (!socket || socket.readyState !== WebSocket.OPEN) return reject(new Error('Uniswap Base websocket is not open')); const requestId = id++; pending.set(requestId, { resolve: resolvePromise, reject }); socket.send(JSON.stringify({ jsonrpc: '2.0', id: requestId, method, params })); });
  let queue = Promise.resolve(); const record = (event: Record<string, unknown>) => { queue = queue.then(() => appendFile(priceFile, `${JSON.stringify({ timestamp: new Date().toISOString(), ...event })}\n`)); return queue; };
  const processLog = async (log: any) => { const address = String(log.address ?? '').toLowerCase(); if (!/^0x[0-9a-f]{40}$/.test(address) || log.topics?.[0]?.toLowerCase() !== SWAP_TOPIC) return; const wallet = addr(log.topics[1]); if (wallet === ZERO) return; const block = Number.parseInt(log.blockNumber ?? '0x0', 16); let activity = activities.get(address); if (!activity) { const pair = await resolve(rpc, address, block); if (!pair || !supported(pair)) return; activity = { pair, events: [] }; activities.set(address, activity); console.log(`[uniswap-v3-base] Pool resolved ${address} ${pair.symbol0}/${pair.symbol1}`); } const now = Date.now(); activity.events = activity.events.filter((event) => event.timestamp >= now - WINDOW_MS); activity.events.push({ wallet, timestamp: now }); const wallets = new Set(activity.events.map((event) => event.wallet)).size; const pair = activity.pair; console.log(`[uniswap-v3-base][websocket] Tracked pool ${address} | swaps=${activity.events.length} | walletCount=${wallets}`); const sqrt = word(log.data, 2); const liquidity = word(log.data, 3); const tick = signed(log.data, 4); const price = (Number(sqrt) / Number(2n ** 96n)) ** 2 * 10 ** (pair.decimals0 - pair.decimals1); if (!Number.isFinite(price) || price <= 0) return; const inverse = 1 / price; const tokenPriceUsd = usd(pair, price, wethUsd); await record({ type: 'price', poolType: 'uniswap_v3_base', poolAddress: address, pair: `${pair.symbol0}/${pair.symbol1}`, price, inversePrice: inverse, tokenPriceUsd, sqrtPriceX96: sqrt.toString(), liquidity: liquidity.toString(), tick, block, fee: pair.fee });
    try { const client = await pgPool.connect(); try { await client.query('BEGIN'); await client.query(`INSERT INTO base_uniswap_v3_prices (pool_address,price,inverse_price,base_token,quote_token,sqrt_price_x96,liquidity,tick,updated_block,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,NOW()) ON CONFLICT (pool_address) DO UPDATE SET price=EXCLUDED.price,inverse_price=EXCLUDED.inverse_price,sqrt_price_x96=EXCLUDED.sqrt_price_x96,liquidity=EXCLUDED.liquidity,tick=EXCLUDED.tick,updated_block=EXCLUDED.updated_block,updated_at=NOW()`, [address, price, inverse, pair.token0, pair.token1, sqrt.toString(), liquidity.toString(), tick, block]); await client.query(`INSERT INTO latest_prices (pool_address,price,inverse_price,price_change,price_change_percent,price_change_direction,fdv_usd,token_price_usd,total_supply,supply_basis,base_reserve,quote_reserve,updated_slot,updated_at) VALUES ($1,$2,$3,NULL,NULL,NULL,NULL,$4,NULL,'uniswap_v3_base',0,0,$5,NOW()) ON CONFLICT (pool_address) DO UPDATE SET price=EXCLUDED.price,inverse_price=EXCLUDED.inverse_price,token_price_usd=EXCLUDED.token_price_usd,price_change=EXCLUDED.price-latest_prices.price,price_change_percent=CASE WHEN latest_prices.price IS NULL OR latest_prices.price=0 THEN NULL ELSE ((EXCLUDED.price-latest_prices.price)/latest_prices.price)*100 END,price_change_direction=CASE WHEN latest_prices.price IS NULL THEN NULL WHEN EXCLUDED.price>latest_prices.price THEN 'up' WHEN EXCLUDED.price<latest_prices.price THEN 'down' ELSE 'flat' END,updated_slot=EXCLUDED.updated_slot,updated_at=EXCLUDED.updated_at`, [address, price, inverse, tokenPriceUsd, now]); await client.query(`INSERT INTO evm_price_history (pool_address,price,inverse_price,updated_block,updated_at) VALUES ($1,$2,$3,$4,NOW())`, [address, price, inverse, block]); for (const timeframe of TIMEFRAMES) { const bucket = Math.floor(now / timeframe.milliseconds) * timeframe.milliseconds; await client.query(`INSERT INTO price_candles (pool_address,timeframe,bucket_start,open,high,low,close,volume,updated_at) VALUES ($1,$2,$3,$4,$4,$4,$4,NULL,NOW()) ON CONFLICT (pool_address,timeframe,bucket_start) DO UPDATE SET high=GREATEST(price_candles.high,EXCLUDED.high),low=LEAST(price_candles.low,EXCLUDED.low),close=EXCLUDED.close,updated_at=EXCLUDED.updated_at`, [address, timeframe.name, bucket, price]); } await client.query(`UPDATE latest_prices AS latest SET high_24h=rolling.high,low_24h=rolling.low FROM (SELECT MAX(high) AS high,MIN(low) AS low FROM price_candles WHERE pool_address=$1 AND timeframe='1m' AND bucket_start >= $2) AS rolling WHERE latest.pool_address=$1`, [address, now - 24 * 60 * 60 * 1000]); await client.query('COMMIT'); } catch (error) { await client.query('ROLLBACK').catch(() => undefined); throw error; } finally { client.release(); } console.log(`[uniswap-v3-base][price] ${pair.symbol0}/${pair.symbol1}=${price} block=${block}`); } catch (error) { await failure(address, error); }
    if (promoted.has(address) || activity.events.length < SWAP_THRESHOLD || wallets < WALLET_THRESHOLD) return; promoted.add(address); try { await pgPool.query(`INSERT INTO base_uniswap_v3_pools (address,pool_type,chain,factory,token0,token0_symbol,token0_decimals,token1,token1_symbol,token1_decimals,fee,tick_spacing,transaction_hash,block_number,discovered_at,indexed_at) VALUES ($1,'uniswap_v3','base',$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,NOW(),NOW()) ON CONFLICT (address) DO UPDATE SET token0=EXCLUDED.token0,token1=EXCLUDED.token1,token0_symbol=EXCLUDED.token0_symbol,token1_symbol=EXCLUDED.token1_symbol,token0_decimals=EXCLUDED.token0_decimals,token1_decimals=EXCLUDED.token1_decimals,fee=EXCLUDED.fee,tick_spacing=EXCLUDED.tick_spacing,block_number=EXCLUDED.block_number,indexed_at=NOW()`, [address, UNISWAP_V3_BASE_FACTORY, pair.token0, pair.symbol0, pair.decimals0, pair.token1, pair.symbol1, pair.decimals1, pair.fee, pair.spacing, log.transactionHash ?? '', block]); console.log(`[uniswap-v3-base] Promoted ${address} ${pair.symbol0}/${pair.symbol1} | swaps=${activity.events.length} | wallets=${wallets}`); } catch (error) { promoted.delete(address); await failure(address, error); }
  };
  const connect = () => { socket = new WebSocket(endpoints[endpointIndex]); socket.on('open', () => { delay = 1000; console.log(`[uniswap-v3-base] websocket connected; global Swap monitoring`); void rpc('eth_subscribe', ['logs', { topics: [SWAP_TOPIC] }]).then((sub) => console.log(`[uniswap-v3-base] global Swap subscription active id=${sub}`)).catch((error) => console.error('[uniswap-v3-base] subscription failed:', error)); }); socket.on('message', (raw) => { try { const payload = JSON.parse(raw.toString()); if (payload.id !== undefined && pending.has(Number(payload.id))) { const request = pending.get(Number(payload.id))!; pending.delete(Number(payload.id)); if (payload.error) request.reject(new Error(JSON.stringify(payload.error))); else request.resolve(payload.result); return; } if (payload.method === 'eth_subscription' && payload.params?.result) void processLog(payload.params.result).catch((error) => void failure(String(payload.params.result?.address ?? ''), error)); } catch (error) { console.error('[uniswap-v3-base] message error:', error); } }); socket.on('error', (error) => console.error('[uniswap-v3-base] websocket error:', error)); socket.on('close', () => { const next = nextWebsocketEndpoint(endpoints, endpointIndex); endpointIndex = next.index; if (!reconnect) { reconnect = setTimeout(() => { reconnect = undefined; connect(); }, delay); delay = Math.min(delay * 2, 30_000); } }); };
  const refreshWeth = async () => { try { wethUsd = await getReferencePrice('weth'); } catch { /* retain last good value */ } };
  await refreshWeth(); setInterval(() => void refreshWeth(), 180_000); connect();
}