import 'dotenv/config';
import { appendFile } from 'node:fs/promises';
import type { Pool as PgPool } from 'pg';
import WebSocket from 'ws';
import { nextWebsocketEndpoint, normalizeWebsocketEndpoints, type WebsocketEndpointInput } from './evm_ws_rotation.js';

export const ROBINHOOD_V4_MANAGER = (process.env.ROBINHOOD_V4_POOL_MANAGER ?? '0x8366a39cc670b4001a1121b8f6a443a643e40951').toLowerCase();
export const ROBINHOOD_V4_POSITION_MANAGER = (process.env.ROBINHOOD_V4_POSITION_MANAGER ?? '0x58daec3116aae6d93017baaea7749052e8a04fa7').toLowerCase();
const SWAP_TOPIC = '0x40e9cecb9f5f1f1c5b9c97dec2917b7ee92e57ba5563708daca94dd84ad7112f';
const POOL_KEYS = '0x86b6be7d';
const ZERO = '0x0000000000000000000000000000000000000000';
const WETH = (process.env.ROBINHOOD_WETH ?? '0x4200000000000000000000000000000000000006').toLowerCase();
const USDG = (process.env.ROBINHOOD_USDG ?? '0x5fc5360d0400a0fd4f2af552add042d716f1d168').toLowerCase();
const PRICE_URL = process.env.ROBINHOOD_PRICE_URL ?? '';
const TIMEFRAMES = [{ name: '1m', milliseconds: 60_000 }, { name: '5m', milliseconds: 300_000 }, { name: '15m', milliseconds: 900_000 }, { name: '1h', milliseconds: 3_600_000 }, { name: '4h', milliseconds: 14_400_000 }, { name: '1d', milliseconds: 86_400_000 }] as const;
const SWAP_THRESHOLD = Number(process.env.ROBINHOOD_V4_SWAP_THRESHOLD ?? process.env.EVM_PROMOTION_SWAP_THRESHOLD ?? process.env.PROMOTION_SWAP_THRESHOLD ?? 100);
const WALLET_THRESHOLD = Number(process.env.ROBINHOOD_V4_MIN_UNIQUE_WALLETS ?? process.env.EVM_PROMOTION_MIN_UNIQUE_WALLETS ?? process.env.PROMOTION_MIN_UNIQUE_WALLETS ?? 20);
const WINDOW_MS = Number(process.env.PROMOTION_WINDOW_MS ?? 15 * 60 * 1000);
const FAILURE_FILE = process.env.ROBINHOOD_V4_FAILURE_FILE ?? 'robinhood-uniswap-v4-failures.jsonl';
const PRICE_FILE = process.env.ROBINHOOD_V4_PRICE_EVENT_FILE ?? 'robinhood-uniswap-v4-price-events.jsonl';
type Pool = { id: string; currency0: string; currency1: string; symbol0: string; symbol1: string; decimals0: number; decimals1: number; fee: number; spacing: number; hooks: string };
type Activity = { pool: Pool; events: Array<{ wallet: string; timestamp: number }> };
const word = (data: string, index: number) => BigInt(`0x${data.replace(/^0x/, '').slice(index * 64, (index + 1) * 64)}`);
const address = (v: unknown) => { const raw = String(v ?? ''); return /^0x[0-9a-f]{64}$/i.test(raw) ? `0x${raw.slice(-40)}`.toLowerCase() : ZERO; };
const signed = (data: string, index: number) => { const raw = word(data, index); return Number(raw >= (1n << 255n) ? raw - (1n << 256n) : raw); };
const text = (v: unknown) => { try { const data = String(v); const offset = Number(word(data, 0)); const length = Number(word(data, offset / 32)); return Buffer.from(data.slice(2 + (offset + 32) * 2, 2 + (offset + 32 + length) * 2), 'hex').toString('utf8').replace(/\0/g, ''); } catch { return ''; } };
const supported = (pool: Pool) => pool.currency0 === WETH || pool.currency1 === WETH || pool.currency0 === USDG || pool.currency1 === USDG;
const usd = (pool: Pool, price: number, wethUsd: number | null) => pool.currency1 === USDG ? price : pool.currency0 === USDG ? 1 / price : pool.currency1 === WETH && wethUsd ? price * wethUsd : pool.currency0 === WETH && wethUsd ? wethUsd / price : null;
async function failure(id: string, error: unknown) { try { await appendFile(FAILURE_FILE, `${JSON.stringify({ timestamp: new Date().toISOString(), poolId: id, error: String(error) })}\n`); } catch { /* best effort */ } }

export async function startRobinhoodUniswapV4Indexer(pgPool: PgPool, websocketUrl: WebsocketEndpointInput, priceFile = PRICE_FILE): Promise<void> {
  const endpoints = normalizeWebsocketEndpoints(websocketUrl);
  if (endpoints.length === 0) { console.warn('[robinhood-v4] ROBINHOOD_V4_WS_URL is not configured; indexing is disabled.'); return; }
  console.log(`[robinhood-v4] Promotion thresholds: swaps=${SWAP_THRESHOLD} uniqueWallets=${WALLET_THRESHOLD} windowMs=${WINDOW_MS}`);
  const activities = new Map<string, Activity>(); const promoted = new Set<string>(); let socket: WebSocket | undefined; let requestId = 1; let endpointIndex = 0; let wethUsd: number | null = null; const pending = new Map<number, { resolve: (v: any) => void; reject: (e: Error) => void }>();
  const rpc = (method: string, params: unknown[]) => new Promise<any>((resolve, reject) => { if (!socket || socket.readyState !== WebSocket.OPEN) return reject(new Error('Robinhood websocket is not open')); const id = requestId++; pending.set(id, { resolve, reject }); socket.send(JSON.stringify({ jsonrpc: '2.0', id, method, params })); });
  const meta = async (token: string) => { if (token === ZERO) return { symbol: 'ETH', decimals: 18 }; const [s, d] = await Promise.all([rpc('eth_call', [{ to: token, data: '0x95d89b41' }, 'latest']), rpc('eth_call', [{ to: token, data: '0x313ce567' }, 'latest'])]); return { symbol: text(s) || token.slice(0, 8), decimals: Number(word(String(d), 0)) }; };
  const resolvePool = async (id: string): Promise<Pool | null> => { const arg = id.slice(2, 52).padEnd(64, '0'); const result = String(await rpc('eth_call', [{ to: ROBINHOOD_V4_POSITION_MANAGER, data: `${POOL_KEYS}${arg}` }, 'latest'])); if (!/^0x[0-9a-f]{320}$/i.test(result)) return null; const currency0 = address(`0x${result.slice(2, 66)}`); const currency1 = address(`0x${result.slice(66, 130)}`); if (currency0 === ZERO && currency1 === ZERO) return null; const [m0, m1] = await Promise.all([meta(currency0), meta(currency1)]); return { id, currency0, currency1, symbol0: m0.symbol, symbol1: m1.symbol, decimals0: m0.decimals, decimals1: m1.decimals, fee: Number(word(result, 2)), spacing: signed(result, 3), hooks: address(`0x${result.slice(258, 322)}`) }; };
  let queue = Promise.resolve(); const record = (event: Record<string, any>) => { queue = queue.then(async () => { await appendFile(priceFile, `${JSON.stringify({ timestamp: new Date().toISOString(), ...event })}\n`, 'utf8'); if (event.type === 'price') { const client = await pgPool.connect(); try { await client.query('BEGIN'); await client.query(`INSERT INTO robinhood_uniswap_v4_prices (pool_id,pool_address,price,inverse_price,base_currency,quote_currency,sqrt_price_x96,liquidity,tick,fee,updated_block,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,NOW()) ON CONFLICT (pool_id) DO UPDATE SET price=EXCLUDED.price,inverse_price=EXCLUDED.inverse_price,sqrt_price_x96=EXCLUDED.sqrt_price_x96,liquidity=EXCLUDED.liquidity,tick=EXCLUDED.tick,fee=EXCLUDED.fee,updated_block=EXCLUDED.updated_block,updated_at=NOW()`, [event.poolId,event.poolId,event.price,event.inversePrice,event.baseCurrency,event.quoteCurrency,event.sqrtPriceX96,event.liquidity,event.tick,event.fee,event.block]); await client.query(`INSERT INTO latest_prices (pool_address,price,inverse_price,token_price_usd,supply_basis,base_reserve,quote_reserve,updated_slot,updated_at) VALUES ($1,$2,$3,$4,'uniswap_v4_robinhood',0,0,$5,NOW()) ON CONFLICT (pool_address) DO UPDATE SET price=EXCLUDED.price,inverse_price=EXCLUDED.inverse_price,token_price_usd=EXCLUDED.token_price_usd,base_reserve=EXCLUDED.base_reserve,quote_reserve=EXCLUDED.quote_reserve,updated_slot=EXCLUDED.updated_slot,updated_at=EXCLUDED.updated_at`, [event.poolId,event.price,event.inversePrice,event.tokenPriceUsd,Date.now()]); await client.query(`INSERT INTO evm_price_history (pool_address,price,inverse_price,updated_block,updated_at) VALUES ($1,$2,$3,$4,NOW())`, [event.poolId,event.price,event.inversePrice,event.block]); await client.query('COMMIT'); } catch (error) { await client.query('ROLLBACK').catch(() => undefined); throw error; } finally { client.release(); } } }).catch((error) => console.error('[robinhood-v4-price] persistence failed:', error)); return queue; };
  const processLog = async (log: any) => { if (String(log.address ?? '').toLowerCase() !== ROBINHOOD_V4_MANAGER || log.topics?.[0]?.toLowerCase() !== SWAP_TOPIC) return; const id = String(log.topics[1] ?? '').toLowerCase(); const wallet = address(log.topics[2]); if (!/^0x[0-9a-f]{64}$/.test(id) || wallet === ZERO) return; let activity = activities.get(id); if (!activity) { const pool = await resolvePool(id); if (!pool || !supported(pool)) return; activity = { pool, events: [] }; activities.set(id, activity); console.log(`[robinhood-v4] Pool resolved ${id} ${pool.symbol0}/${pool.symbol1}`); } const now = Date.now(); activity.events = activity.events.filter((e) => e.timestamp >= now - WINDOW_MS); activity.events.push({ wallet, timestamp: now }); const wallets = new Set(activity.events.map((e) => e.wallet)).size; const pool = activity.pool; console.log(`[robinhood-v4] Tracked pool ${id} | swaps=${activity.events.length} | walletCount=${wallets}`); const sqrt = word(log.data, 2); const liquidity = word(log.data, 3); const tick = signed(log.data, 4); const price = (Number(sqrt) / Number(2n ** 96n)) ** 2 * 10 ** (pool.decimals0 - pool.decimals1); if (!Number.isFinite(price) || price <= 0) return; const inverse = 1 / price; if (promoted.has(id) || activity.events.length < SWAP_THRESHOLD || wallets < WALLET_THRESHOLD) return; try { await pgPool.query(`INSERT INTO robinhood_uniswap_v4_pools (address,pool_type,chain,manager,pool_id,currency0,currency0_symbol,currency0_decimals,currency1,currency1_symbol,currency1_decimals,fee,tick_spacing,hooks,sqrt_price_x96,tick,transaction_hash,block_number,discovered_at,indexed_at) VALUES ($1,'uniswap_v4','robinhood',$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,NOW(),NOW()) ON CONFLICT (address) DO UPDATE SET block_number=EXCLUDED.block_number,indexed_at=NOW()`, [id, ROBINHOOD_V4_MANAGER, id, pool.currency0, pool.symbol0, pool.decimals0, pool.currency1, pool.symbol1, pool.decimals1, pool.fee, pool.spacing, pool.hooks, sqrt.toString(), tick, log.transactionHash ?? '', Number.parseInt(log.blockNumber ?? '0x0', 16)]); promoted.add(id); console.log(`[robinhood-v4] Promoted ${id} ${pool.symbol0}/${pool.symbol1} | swaps=${activity.events.length} | wallets=${wallets}`); await record({ type: 'price', poolType: 'uniswap_v4_robinhood', poolId: id, poolAddress: id, manager: ROBINHOOD_V4_MANAGER, positionManager: ROBINHOOD_V4_POSITION_MANAGER, pair: `${pool.symbol0}/${pool.symbol1}`, price, inversePrice: inverse, tokenPriceUsd: usd(pool, price, wethUsd), baseCurrency: pool.currency0, quoteCurrency: pool.currency1, sqrtPriceX96: sqrt.toString(), liquidity: liquidity.toString(), tick, fee: pool.fee, block: Number.parseInt(log.blockNumber ?? '0x0', 16) }); } catch (error) { await failure(id, error); console.error(`[robinhood-v4] Promotion failed ${id}:`, error); } };
  const connect = () => { const endpoint = endpoints[endpointIndex]; socket = new WebSocket(endpoint); socket.on('open', () => { console.log(`[robinhood-v4] websocket connected on ${endpoint}`); void rpc('eth_subscribe', ['logs', { address: ROBINHOOD_V4_MANAGER, topics: [SWAP_TOPIC] }]).then((id) => console.log(`[robinhood-v4] Swap subscription active id=${id}`)); }); socket.on('message', (raw) => { try { const payload = JSON.parse(raw.toString()); if (payload.id !== undefined && pending.has(Number(payload.id))) { const request = pending.get(Number(payload.id))!; pending.delete(Number(payload.id)); if (payload.error) request.reject(new Error(JSON.stringify(payload.error))); else request.resolve(payload.result); return; } if (payload.method === 'eth_subscription' && payload.params?.result) void processLog(payload.params.result).catch((error) => void failure(String(payload.params.result?.topics?.[1] ?? ''), error)); } catch (error) { console.error('[robinhood-v4] message error:', error); } }); socket.on('error', (error) => console.error('[robinhood-v4] websocket error:', error)); socket.on('close', () => { const next = nextWebsocketEndpoint(endpoints, endpointIndex); endpointIndex = next.index; setTimeout(connect, 2000); }); };
  connect();
}